etn-ccis/blui-react-themes

README.md

- link to npm from badge
- 
- 
-

link out to npm from badge

---

yarn.lock

- Remove old deps by running `yarn`.  New lock file.

Remove deps from yarn lock

---

package.json

Update submodule pointer and update install:dependencies script

Update submodule pointer and update install:dependencies script

---

src/blueTheme.ts

Fixes # .
- Fix hover bg mobile for filled input on mobile devices.

Fix mobile bg

---

package.json
scripts/build.sh
scripts/buildTest.sh

Fixes # .
- copy licenses json over for dist
- update test
- 
- 
open branch
remove licenses json from root
run yarn precommit

include licenses json in dist

---

CHANGELOG.md
CommonOverrides.md
package.json
yarn.lock

Fixes BLUI-3660 && #47.
- Remove @mui/styles dependency and update CommonOverrides
- yarn start

Remove @mui/styles dependency and update CommonOverrides

---

CHANGELOG.md
package.json

Prepare to publish v7.1.0

---

.gitmodules
CHANGELOG.md
CODEOWNERS
LICENSES.json
README.md
package.json

- Updated all links to their GHE equivalences
- Updated Codeowners

Update GHE links and code owners

---

.github/pr-labeler.yml
.github/workflows/pr-labeler.yml

Fixes  BLUI-3749 .
- labeler workflow
-
-
-
- verify brightlayer-ui label placed on open PR
-

add labeler

---

CHANGELOG.md
src/blueDarkTheme.ts

Fixes https://github.com/etn-ccis/blui-react-themes/issues/46 .
- update mui backdrop style override to include invisible & transparent
-
-
-
- clone repo
- yarn start
- switch to dark mode
- open user menu from brightlayer-ui-components/data-display-components
- verify backdrop transparent 
-

update backdrop theme override

---

CHANGELOG.md
README.md
package.json

- Update change log date, update package version and add install section back in read me
-
-
-
-
-

Prepare release 7.2.0

---

.github/workflows/blui-ci.yml

Fixes # .
- use npm publish
-
-
-
-
-

use npm publish

---

CHANGELOG.md
README.md
package.json

- Updated docs for MUI 6
- Updated package version
- Updated change log

MUI 6 Docs and publish

---

src/componentStylesOverrides/MuiChip.ts

Fixes # .
- Fixed chip disable color issue 
-
- yarn run
-

chip disable color issue fix

---

README.md
src/index.ts

- Clarify some wording in the readme
- Read the Readme and make sure it makes sense

chore: wordsmith the readme

---

src/componentStylesOverrides/MuiAvatar.ts

Added dark mode color for avatar

---

README.md

Added note about applying styles

---

CHANGELOG.md
package.json

- Version upgraded & changelog updated
-
-
- 
-
-

Package version upgraded

---

CHANGELOG.md

Date changed at changelog

---

src/componentStylesOverrides/MuiButton.ts
src/componentStylesOverrides/MuiChip.ts
src/componentStylesOverrides/MuiSwitch.ts

Fixes # .
https://github.com/etn-ccis/blui-react-themes/issues/135
https://github.com/etn-ccis/blui-react-themes/issues/134
https://github.com/etn-ccis/blui-react-themes/issues/130
https://github.com/etn-ccis/blui-react-themes/issues/129
-
-
-

fixes for react themes

---

CHANGELOG.md
package.json

release version for react-themes

---

src/componentStylesOverrides/MuiSnackbarContent.ts

Fixes # . BLUI-6708
Before Fix : 
After Fix :
-
-
-
-
-
-

Fixed snackbar black theme issue

---

src/componentStylesOverrides/MuiStepIcon.ts

Fixes # . BLUI-6708
Before Fix:
After Fix:
-
-
-
-
-
-

fixed stepper dark theme color issue

---

src/componentStylesOverrides/MuiBottomNavigationAction.ts
src/componentStylesOverrides/MuiChip.ts
src/componentStylesOverrides/MuiTab.ts

Fixes 
[137](https://github.com/etn-ccis/blui-react-themes/issues/137) .
[67](https://github.com/etn-ccis/blui-react-themes/issues/67)
-
-
-
-
-

add color for dark theme

---

src/componentStylesOverrides/MuiButton.ts

Fixes # .
[111](https://github.com/etn-ccis/blui-react-themes/issues/111)
[50](https://github.com/etn-ccis/blui-react-themes/issues/50)
-
-
-
-
-
-

fixed button color issue

---

CHANGELOG.md
package.json

Fixes # .
- Package.json version & Change log updated.
-
-
-
-
-

Publish minor version 8.1.1

---

CHANGELOG.md
src/componentStylesOverrides/MuiBottomNavigationAction.ts
src/componentStylesOverrides/MuiChip.ts
src/componentStylesOverrides/MuiSlider.ts

Date change for package release

---

CHANGELOG.md

Date Change

---

CHANGELOG.md

Updated the publish date

---

README.md

Fixes https://eaton-corp.atlassian.net/browse/BLUI-6743 .
- updated README file to redirect contributors to the monorepo.
-
-
-
-

Added archive message
